/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckIcon: typeof import('./src/components/Icons/CheckIcon.vue')['default']
    DocumentIcon: typeof import('./src/components/Icons/DocumentIcon.vue')['default']
    DoubleCheckIcon: typeof import('./src/components/Icons/DoubleCheckIcon.vue')['default']
    IconPicker: typeof import('./src/components/IconPicker.vue')['default']
    Popover: typeof import('./src/components/frappe-ui/Popover.vue')['default']
    ReactIcon: typeof import('./src/components/Icons/ReactIcon.vue')['default']
    ReplyAllIcon: typeof import('./src/components/Icons/ReplyAllIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmileIcon: typeof import('./src/components/Icons/SmileIcon.vue')['default']
    WhatsAppIcon: typeof import('./src/components/Icons/WhatsAppIcon.vue')['default']
    WhatsappTemplateSelectorModal: typeof import('./src/components/WhatsappTemplateSelectorModal.vue')['default']
  }
}
